### PR TITLE
Fix #57: Cannot remove observer from inside the observing block

### LINKED ISSUE #57: Cannot remove observer from inside the observing block
When i want to remove observation outside the observation block:
```
self.simpleObject = [SimpleObject new];
[self.KVOController observe:self.simpleObject
                    keyPath:NSStringFromSelector(@selector(simpleProperty))
                    options:NSKeyValueObservingOptionInitial|NSKeyValueObservingOptionNew
                      block:^(AppDelegate *observer, id object, NSDictionary *change) {
                          
}];
    
[self.KVOController unobserve:self.simpleObject];
```
then everything is fine, but when i want to remove observer from inside the block
```
self.simpleObject = [SimpleObject new];
[self.KVOController observe:self.simpleObject
                    keyPath:NSStringFromSelector(@selector(simpleProperty))
                    options:NSKeyValueObservingOptionInitial|NSKeyValueObservingOptionNew
                      block:^(AppDelegate *observer, id object, NSDictionary *change) {
                            [observer.KVOController unobserve:observer.simpleObject];
}];
```

then i got crash, is it done by design or is it a bug?

```
Terminating app due to uncaught exception 'NSRangeException', reason: 'Cannot remove an observer <_FBKVOSharedController 0x7fa62a62d350> for the key path "simpleProperty" from <SimpleObject 0x7fa62a62b890> because it is not registered as an observer.
```

### PR DESCRIPTION
**Pull request by siyusong**
Fix #57.

The reason I think this is a bug in KVOController can be found in [my comments on that issue](https://github.com/facebook/KVOController/issues/57#issuecomment-186692781).

One new unit test has been added.

### CODE REVIEW

**Comment by kimon** [comment]
updating configs and moving to new CI. will circle back once we've stabelized

File: FBKVOController/FBKVOController.m [hunk 1]
```diff
@@ -268,6 +273,14 @@ - (void)observe:(id)object info:(_FBKVOInfo *)info
   
   // add observer
   [object addObserver:self forKeyPath:info->_keyPath options:info->_options context:(void *)info];
+
+  info->_registered = YES;
```
Comment (nlutsenko) [inline FBKVOController/FBKVOController.m]: You can actually get away here with just a single enum here, instead of 2 variables.
For example:
```objc
typedef NS_ENUM(uint8_t, _FBKVOInfoState) {
  _FBKVOInfoStateInitial = 0,
  _FBKVOInfoStateObserving,
  _FBKVOInfoStateNotObserving
}
```

And then you would simply remove the observer from the object in this very method if it is unobserved, otherwise you would set the state to observed.

File: FBKVOController/FBKVOController.m [hunk 2]
```diff
@@ -275,12 +288,20 @@ - (void)unobserve:(id)object info:(_FBKVOInfo *)info
...
     return;
   }
-  
+
+  if (!info->_registered) {
+      // this could happen when `NSKeyValueObservingOptionInitial` is one of the NSKeyValueObservingOptions.
+      // we cannot unobserve them right now because they are not technially observers yet.
+      // instead, we set a flag so they can be unobserved later, after the `addObserver` call returns.
+      info->_unregisteredBeforeRegistered = YES;
+      return;
```
Comment (nlutsenko) [inline FBKVOController/FBKVOController.m]: Bailing out early here will actually never remove the observation info from this context - instead you probably would want to check the above mentioned state and guard the actual `removeObserver:forKeyPath:context:` which is the source of the problem.

File: FBKVOController/FBKVOController.m [hunk 3]
```diff
@@ -294,13 +315,22 @@ - (void)unobserve:(id)object infos:(NSSet *)infos
   // unregister info
   OSSpinLockLock(&_lock);
   for (_FBKVOInfo *info in infos) {
-    [_infos removeObject:info];
+    if (info->_registered) {
```
Comment (nlutsenko) [inline FBKVOController/FBKVOController.m]: Same as above method - this will never remove the `info` from the `_infos` table, and will persist it forever.
Instead - we should guard only the `removeObserver` method on the infos.

**Comment by nlutsenko** [comment]
@siyusong put in few important thoughts, we are closer to being stable in CI/Configs, so can iterate on this change together with you.

File: FBKVOController/FBKVOController.m (hunk 2 above)
Comment (siyusong) [inline FBKVOController/FBKVOController.m]: Thanks for the feedback! Although I am not 100% sure what you mean here. In my current implementation, if we are unobserving the observer inside the block with `.Initial` option set, `- unobserve:info(s):` method will actually got called twice: (1) inside the block, and (2) from `- observe:info:` method.

Although it will left the observation info in the context at first, `info` will be removed the second time we attempt to unobserve it. I have verified that `_infos.count == 0` at the time the call to `- observe:info:` returns.

However, I think the implementation could become simpler if we implement it as you suggested - I think we still need to call `- unobserve:` twice, but removing the same `info` object twice from the NSHashTable seems harmless, so I will give it a try.

Comment (nlutsenko) [inline FBKVOController/FBKVOController.m]: Sounds good. You are right, nevermind those comments - since you are calling it twice the first pass will remove it, the first will be a no-op and the second call will remove the observation. For some reason I constantly make mistakes in basic boolean logic on Fridays. (@richardjrossiii can confirm this).

It might be worth exploring the optimization where you don't need to call `unobserve:` twice, since the only piece that you need to guard is `removeObserver:` method call.

Here is the rough logic in my head around this optimization:

`-observe`:
After `addObserver:` call - if state is `.Initial` - then we change it to `.Observing`, otherwise we call `removeObserver:`.

`-unobserve`:
`.Observing` state - remove the object from the `infos` hash table + `removeObserver` is called inside `unobserve`.
`.Unobserved` state - remove the object from the `infos` hash table.

**Comment by nlutsenko** [comment]
@siyusong, any chance this is coming soon? I would love to release and tag this...

**Comment by siyusong** [comment]
@nlutsenko Sorry for the delay! I will find some time to work on this today.

**Comment by siyusong** [comment]
Here's my implementation with a single enum instead of two booleans. I am still guarding `_infos removeObject:` instead of `removeObserver:` because I don't want to leave KVOController in a state where an existing added observer does not have its corresponding `info`. I don't think we can avoid calling `unobserve` twice since the first call is made by the client of the library, and we have to actually unobserve it later after the `addObserver:` call returns (this case covered by the new unit test).

**Comment by nlutsenko** [comment]
Removing the objects from infos won't cause any problems, also I would rather have initial `unobserve` method call remove the object from infos, rather than removing this in the second call.
This will make sure that if any observation call happens - we won't continue calling into observer after we called unobserve, since we ignore stuff that comes from objects that don't have corresponding infos.

Also, it will simplify all these checks and logic and will make it consistent in between a single unobserve and multiple unobserve methods, that are hard to grasp right now.

What do you think? I vote for updating it to a simpler logic...

**Comment by siyusong** [comment]
@nlutsenko +1 to making the logic simpler / more consistent. I made the change to guard the `removeObserver:` calls.

File: FBKVOControllerTests/FBKVOControllerTests.m [hunk 4]
```diff
@@ -308,6 +308,26 @@ - (void)testObserveKeyPathsOptionsContextObservesEachOfTheKeyPaths
                                                   context:NULL];
 }
 
+- (void)testObserveKeyPathsOptionsContextUnobserveWithinBlockWithOptionInitial
```
Comment (nlutsenko) [inline FBKVOControllerTests/FBKVOControllerTests.m]: I am so sorry that I've missed this. This test is 4 spaces indented, where the code standard is 2 spaces :)
It's probably as simple as running auto-indent in Xcode...

File: FBKVOController/FBKVOController.m [hunk 5]
```diff
@@ -275,14 +298,22 @@ - (void)unobserve:(id)object info:(_FBKVOInfo *)info
...
+
   // remove observer
-  [object removeObserver:self forKeyPath:info->_keyPath context:(void *)info];
+  if (info->_state == _FBKVOInfoStateObserving) {
+    [object removeObserver:self forKeyPath:info->_keyPath context:(void *)info];
+  } else {
+    // this could happen when `NSKeyValueObservingOptionInitial` is one of the NSKeyValueObservingOptions.
+    // we cannot unobserve them right now because they are not technially observers yet.
+    // instead, we set a flag so they can be unobserved later, after the `addObserver` call returns.
+    info->_state = _FBKVOInfoStateNotObserving;
```
Comment (nlutsenko) [inline FBKVOController/FBKVOController.m]: You probably want to set this always, regardless of whether you are unobserving via KVO API or not.
This will prevent double calls to `removeObserver:`.

File: FBKVOController/FBKVOController.m [hunk 6]
```diff
@@ -268,6 +280,17 @@ - (void)observe:(id)object info:(_FBKVOInfo *)info
   
   // add observer
   [object addObserver:self forKeyPath:info->_keyPath options:info->_options context:(void *)info];
+
+  // this could happen when `NSKeyValueObservingOptionInitial` is one of the NSKeyValueObservingOptions,
+  // and the observer is unregistered within the callback block.
+  // at this time the object has been registered as an observer (in Foundation KVO),
+  // so we can safely unobserve it if we need to.
+  BOOL shouldUnobserve = info->_state == _FBKVOInfoStateNotObserving;
```
Comment (nlutsenko) [inline FBKVOController/FBKVOController.m]: I believe this actually could be simplified into:
```objc
if (info->_state == _FBKVOInfoStateInitial) {
  info->_state = FBKVOInfoStateObserving;
} else {
  [object removeObserver:self forKeyPath:info->_keyPath options:info->_options context:(void *)info];
}
```

It has the same guarantees, but probably is a tad faster, since you are not going to perform lock/remove/unlock?
I can merge it this way though as well, it looks fine and provides the same guarantees.

**Comment by nlutsenko** [comment]
@siyusong, so sorry for missing these nits, I promise this is the last iteration.
Also, if you could squash all commits into a single one - that would be just phenomenal...

**Comment by siyusong** [comment]
@nlutsenko No worries! Those are all good points that make the code simpler. Please take a look at this (hopefully) last iteration :smiley: 

While you are merging pull request, can you also take a look at my other pull request (#84)?

**Comment by nlutsenko** [comment]
Looks great! Thank you for bearing with me through the process and for this awesome contribution! Merging now...
